version: "3"
services:
  bmi-demo-db:
    image: postgres:12.6-alpine
    container_name: bmi-demo-db
    environment:
      POSTGRES_PASSWORD: "test"
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh